  combine-dnas[m
  develop[m
  facets[m
  feature/5-agent-API-bindings[m
  feature/economic-events[m
  feature/join-forms-to-api[m
  feature/offers[m
  feature/recipes[m
  feature/save_plan[m
  feature/units[m
  full-ui[m
  github-issues[m
  hc_0_3[m
  hc_0_3-combined-dnas[m
* [32mmain[m
  package-app[m
  save-plan-updated-merge[m
  static-data[m
  trash[m
  try_fix_nav_links[m
  update_plans_new[m
  upgrade-0.2[m
  upgrade-hrea-holochain-0.2[m
