[package]
name = "migrate"
version = "0.0.1"
edition = "2021"

[lib]
crate-type = ["cdylib", "rlib"]
name = "migrate"

[dependencies]
hdk = { workspace = true }

serde = { workspace = true }

migrate_integrity = { workspace = true } 
